version: '3'

name: kong-keycloak-ldap

services:
  openldap:
    image: bitnami/openldap:2.5.18
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP_CUSTOM_LDIF_DIR=/ldifs
      - LDAP_CUSTOM_SCHEMA_DIR=/schemas
      # see https://www.openldap.org/doc/admin26/slapdconfig.html loglevel
      #   (8 or 32 or 64 or 128 or 256 or 512 or 1024 or 2048) = 4072
      # - LDAP_LOGLEVEL=4072
      # - BITNAMI_DEBUG=true
    volumes:
      - ./ldifs:/ldifs
  #      - ./schemas:/schemas

  keycloak-db:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak

  keycloak:
    image: bitnami/keycloak:25.0.2
    ports:
      - "8180:8080"
    #      - '8443:8443'
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=keycloak-db
      - KEYCLOAK_EXTRA_ARGS=--import-realm
    volumes:
      - ./keycloak-config/realm:/opt/bitnami/keycloak/data/import